LASB-815: I have removed code that is not related to data migration o…
ministryofjustice/laa-crime-means-assessment pull request #51
Opened 2022-01-13 13:32 UTC by lucas-e-t

…r any other relevant functionality

## What

[Link to story](https://dsdmoj.atlassian.net/browse/LASB-815)

Describe what you did and why:
I removed all reference to Defendant assessment controller as it is not related to migration functionality. All functionality regarding DeffendantAssessment was an exercise related to LASB-759 in order to introduce Postgres and liquibase support to crime-means-assessment.

## Checklist

Before you ask people to review this PR:

- [x] Tests should be passing: `./gradlew test`
- [x] Github should not be reporting conflicts; you should have recently run `git rebase master`.
- [x] Avoid mixing whitespace changes with code changes in the same commit. These make diffs harder to read and conflicts more likely.
- [x] You should have looked at the diff against master and ensured that nothing unexpected is included in your changes.
- [x] You should have checked that the commit messages say why the change was made.

2022-01-14 17:17 UTC, Mhowell494 requested changes
Great work, just one small change that needs making

2022-01-14 17:17 UTC, Mhowell494 commented on crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/exception/RestControllerAdviser.java
>      public ResponseEntity<ErrorDTO> handleDefendantAssessmentInternalServerError(RuntimeException ex) {
The name of this method needs to be changed to something more appropriate.

2022-01-21 01:47 UTC, msahilan07 approved these changes

2022-01-21 17:11 UTC, Mhowell494 approved these changes

2022-01-21 17:18 UTC, merged