LASB-778
ministryofjustice/laa-crime-means-assessment pull request #70
Opened 2022-02-18 10:10 UTC by rajkrk

## What

[Link to story](https://dsdmoj.atlassian.net/browse/LASB-778)

LASB-778 Added validations integrating with maat court data api, updated dependencies and fixed applications startup issues

## Checklist

Before you ask people to review this PR:

- [*] Tests should be passing: `./gradlew test`
- [*] Github should not be reporting conflicts; you should have recently run `git rebase main`.
- [*] Avoid mixing whitespace changes with code changes in the same commit. These make diffs harder to read and conflicts more likely.
- [*] You should have looked at the diff against main and ensured that nothing unexpected is included in your changes.
- [*] You should have checked that the commit messages say why the change was made.

2022-02-18 11:04 UTC, Mhowell494 commented on crime-means-assessment/src/main/resources/schemas/apiCreateMeansAssessmentRequest.json
> +    "reservationId": {
This is the same as the RepID, I've created a separate UserSession object in the changes I've made in another branch, so I can sort this out when I merge.

2022-02-18 11:12 UTC, Mhowell494 commented on crime-means-assessment/src/main/java/uk/gov/justice/laa/crime/meansassessment/validation/service/MeansAssessmentValidationService.java
> +    public void initializeWebClient() {
Can we not do this in the MaatApiOAuth2Client class? There is a lot of configuration being done in there and I think it makes sense to centralise it.

2022-02-18 11:14 UTC, Mhowell494 requested changes
I think we could do with making a few small changes and restoring the AssessmentCriteriaService.

2022-02-18 15:50 UTC, msahilan07 approved these changes

2022-02-21 11:43 UTC, Mhowell494 approved these changes

2022-02-21 12:02 UTC, merged